export const mockCards = [
  {
    id: "1",
    nickname: "Luna",
    age: 22,
    city: "Norway",
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=400&q=80", // added additional image
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=400&q=80", // added additional image
    ],
    videos: [
      "https://videos.pexels.com/video-files/28679998/12451525_1440_2560_30fps.mp4",

    ],
    isNew: true,
    isTopped: true,
    isAvailable: true,
    weight: "54",
    height: "168",
    chestSize: "34B",
    hairColor: ["Blonde", "Straight"],
    hasTattoo: false,
    hasPiercing: false,
    isSmoker: false,
    shaveStatus: "Shaved",
    experience: "profi",
    serviceType: "Modeling",
    nationality: "Norwegian",
    languages: ["English", "Norwegian"],
    servicesFor: ["Photoshoot", "Fashion"],
    description: "A professional model with experience in fashion.",
    services: ["Photoshoot", "Catalog"],
    otherSpecialServices: ["Private sessions"],
    phoneNumber: "123-456-7890",
  },
  {
    id: "2",
    nickname: "Maya",
    age: 24,
    city: "Canada",
    images: [
      "https://images.unsplash.com/photo-1468071174046-657d9d351a40?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=400&q=80",
    ],
    videos: [
      "https://www.w3schools.com/html/mov_bbb.mp4", // added video
      "https://www.w3schools.com/html/movie.mp4", // added video
      "https://www.w3schools.com/html/movie.mp4", // added video
    ],
    isNew: false,
    isTopped: false,
    availability: false,
    weight: "58",
    height: "172",
    chestSize: "36C",
    hairColor: ["Brown", "Wavy"],
    hasTattoo: true,
    hasPiercing: true,
    isSmoker: true,
    shaveStatus: "Not shaved",
    experience: "advanced",
    serviceType: "Modeling",
    nationality: "Canadian",
    languages: ["English", "French"],
    servicesFor: ["Fashion", "Commercial"],
    description:
      "Experienced in both high-end fashion and commercial modeling.",
    services: ["Photoshoot", "Commercial"],
    otherSpecialServices: ["Private sessions"],
    phoneNumber: "987-654-3210",
  },
  {
    id: "3",
    nickname: "Ella",
    age: 21,
    city: "Sweden",
    images: [
      "https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=400&q=80",
    ],
    videos: [
      "https://www.w3schools.com/html/mov_bbb.mp4", // added video
      "https://www.w3schools.com/html/movie.mp4", // added video
    ],
    isNew: false,
    isTopped: true,
    availability: true,
    weight: "53",
    height: "165",
    chestSize: "34A",
    hairColor: ["Red", "Curly"],
    hasTattoo: false,
    hasPiercing: false,
    isSmoker: false,
    shaveStatus: "Shaved",
    experience: "amateur",
    serviceType: "Modeling",
    nationality: "Swedish",
    languages: ["English", "Swedish"],
    servicesFor: ["Fashion", "Commercial"],
    description:
      "A rising model with a passion for fashion and editorial shoots.",
    services: ["Fashion Show", "Photoshoot"],
    otherSpecialServices: ["Private sessions", "Events"],
    phoneNumber: "321-654-9870",
  },
  {
    id: "4",
    nickname: "Sophie",
    age: 26,
    city: "New Zealand",
    images: [
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=400&q=80",
    ],
    videos: [
      "https://www.w3schools.com/html/mov_bbb.mp4", // added video
      "https://www.w3schools.com/html/movie.mp4", // added video
      "https://www.w3schools.com/html/movie.mp4", // added video
    ],
    isNew: true,
    isTopped: false,
    availability: true,
    weight: "60",
    height: "175",
    chestSize: "36B",
    hairColor: ["Black", "Straight"],
    hasTattoo: false,
    hasPiercing: true,
    isSmoker: false,
    shaveStatus: "Not shaved",
    experience: "advanced",
    serviceType: "Modeling",
    nationality: "New Zealander",
    languages: ["English"],
    servicesFor: ["Photoshoot", "Catalog", "Runway"],
    description:
      "Experienced and versatile model with a focus on runway and catalog.",
    services: ["Photoshoot", "Runway"],
    otherSpecialServices: ["Private sessions"],
    phoneNumber: "876-543-2109",
  },
  {
    id: "5",
    nickname: "Zara",
    age: 23,
    city: "Iceland",
    images: [
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1447078806655-40579c2520d6?auto=format&fit=crop&w=400&q=80",
    ],
    videos: [
      "https://www.w3schools.com/html/mov_bbb.mp4", // added video
      "https://www.w3schools.com/html/movie.mp4", // added video
    ],
    isNew: false,
    isTopped: true,
    availability: false,
    weight: "57",
    height: "169",
    chestSize: "35C",
    hairColor: ["Brown", "Wavy"],
    hasTattoo: true,
    hasPiercing: false,
    isSmoker: true,
    shaveStatus: "Not shaved",
    experience: "profi",
    serviceType: "Modeling",
    nationality: "Icelandic",
    languages: ["Icelandic", "English"],
    servicesFor: ["Photoshoot", "Catalog"],
    description:
      "A well-rounded model experienced in both editorial and commercial.",
    services: ["Photoshoot", "Catalog"],
    otherSpecialServices: ["Private sessions", "Events"],
    phoneNumber: "231-543-7890",
  },
  {
    id: "6",
    nickname: "Nina",
    age: 25,
    city: "Austria",
    images: [
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&q=80",
    ],
    videos: [
      "https://www.w3schools.com/html/mov_bbb.mp4", // added video
      "https://www.w3schools.com/html/movie.mp4", // added video
    ],
    isNew: true,
    isTopped: false,
    availability: true,
    weight: "55",
    height: "167",
    chestSize: "34B",
    hairColor: ["Blonde", "Straight"],
    hasTattoo: false,
    hasPiercing: false,
    isSmoker: false,
    shaveStatus: "Shaved",
    experience: "profi",
    serviceType: "Modeling",
    nationality: "Austrian",
    languages: ["German", "English"],
    servicesFor: ["Photoshoot", "Catalog"],
    description:
      "A professional with a strong presence in both runway and editorial.",
    services: ["Photoshoot", "Catalog"],
    otherSpecialServices: ["Private sessions", "Fashion"],
    phoneNumber: "543-678-9876",
  },
];
